// <auto-generated />
namespace WebSocial.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class changeLanguage1stTry : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeLanguage1stTry));
        
        string IMigrationMetadata.Id
        {
            get { return "201312221702229_changeLanguage1stTry"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
